version: '3'

services:
  mongo:
    image: mongo
    container_name: liquefier-mongo
    command: mongod --replSet liquefierReplica
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongo:/data/db
