"""empty message

Revision ID: 04fdd1605963
Revises: 88abf79c3053
Create Date: 2023-11-28 19:33:29.957447

"""
from alembic import op
import sqlalchemy as sa


revision = "04fdd1605963"
down_revision = "88abf79c3053"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic_rule",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("topic_id", sa.String(length=36), nullable=False),
        sa.Column("transformers", sa.JSON(), nullable=True),
        sa.Column("output", sa.String(length=100), nullable=True),
        sa.Column("extras", sa.JSON(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topic_rule_created_at"), "topic_rule", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_topic_rule_id"), "topic_rule", ["id"], unique=False)
    op.create_index(
        op.f("ix_topic_rule_is_deleted"), "topic_rule", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_topic_rule_status"), "topic_rule", ["status"], unique=False)
    op.create_index(
        op.f("ix_topic_rule_topic_id"), "topic_rule", ["topic_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topic_rule_topic_id"), table_name="topic_rule")
    op.drop_index(op.f("ix_topic_rule_status"), table_name="topic_rule")
    op.drop_index(op.f("ix_topic_rule_is_deleted"), table_name="topic_rule")
    op.drop_index(op.f("ix_topic_rule_id"), table_name="topic_rule")
    op.drop_index(op.f("ix_topic_rule_created_at"), table_name="topic_rule")
    op.drop_table("topic_rule")
    # ### end Alembic commands ###
