"""empty message

Revision ID: 6b0eb25c649d
Revises: 04fdd1605963
Create Date: 2023-11-30 00:46:12.953748

"""
from alembic import op
import sqlalchemy as sa


revision = "6b0eb25c649d"
down_revision = "04fdd1605963"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topic_rule", sa.Column("name", sa.String(length=255), nullable=True))
    op.drop_index("ix_topic_rule_topic_id", table_name="topic_rule")
    op.create_index(
        op.f("ix_topic_rule_topic_id"), "topic_rule", ["topic_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topic_rule_topic_id"), table_name="topic_rule")
    op.create_index("ix_topic_rule_topic_id", "topic_rule", ["topic_id"], unique=False)
    op.drop_column("topic_rule", "name")
    # ### end Alembic commands ###
